use std::time::Instant;

/// events generated by kernel interactions with the component.
#[derive(Debug)]
pub enum ComponentEvent {
  Attached { name: String },
  Detached { name: String },
  Update { delta: Instant },
}

/// Window events are generated in response to window events coming from
/// the windowing system.
#[derive(Debug)]
pub enum WindowEvent {
  Close,
  Resize { width: u32, height: u32 },
}

/// Kernel events are generated by the kernel itself
#[derive(Debug)]
pub enum KernelEvent {
  Initialized,
  Shutdown,
}

/// Generic Event Enum which encapsulates all possible events that will be
/// emitted by the LambdaKernel
#[derive(Debug)]
pub enum Events {
  Component {
    event: ComponentEvent,
    issued_at: Instant,
  },
  Window {
    event: WindowEvent,
    issued_at: Instant,
  },
  Kernel {
    event: KernelEvent,
    issued_at: Instant,
  },
}
