/**
 * @file engine/src/core/Window.h
 * @brief The Abstract Window definition.
 */
#ifndef ENGINE_SRC_CORE_WINDOW_H_
#define ENGINE_SRC_CORE_WINDOW_H_

#include <string>

#include "core/Core.h"
#include "core/events/Event.h"

namespace engine {

/**
 * @struct WindowProperties
 * @brief Generic Window properties used to create platform specific windows.
 */
struct WindowProperties {
  std::string Title;
  unsigned int Width;
  unsigned int Height;

  WindowProperties(
      const std::string& title = "Game Engine",
      unsigned int width = 1280,
      unsigned int height = 720)
          : Title(title), Width(width), Height(height) {}
};


/**
 * @class Window
 * @brief The generic window implementation that allows platform specific window
 * APIs to expose generic window functionality without users having to know the
 * window system.
 */
class ENGINE_API Window {
 public:
  /**
   * @typedef EventCallbackFunction
   * @brief The function to be used for handling events generated by user input
   * in the window.
   */
  typedef std::function<void(events::Event*)> EventCallbackFunction;
  virtual ~Window() {}

  /**
   * @fn OnUpdate
   * @brief Handles what the window should do when the engine updates.
   */
  virtual void OnUpdate() = 0;

  /**
   * @fn GetWidth
   * @brief Get the width of the window.
   */
  virtual unsigned int GetWidth() const = 0;

  /**
   * @fn GetHeight
   * @brief Get the height of the window.
   */
  virtual unsigned int GetHeight() const = 0;

  /**
   * @fn SetEventCallback
   * @brief Set the callback for the window when an event is generated.
   */
  virtual void SetEventCallback(const EventCallbackFunction& callback) = 0;

  /**
   * @fn SetVerticalSync
   * @brief Set the vertical sync on the window.
   */
  virtual void SetVerticalSync(bool enabled) = 0;

  /**
   * @fn HasVerticalSync
   * @brief Checks if the window has vertical sync enabled.
   */
  virtual bool HasVerticalSync() const = 0;

  /**
   * @fn GetNativeWindow
   * @brief Get the native window implementation. Needs to be casted into it's
   * real type.
   */
  virtual void* GetNativeWindow() const = 0;

  /**
   * @fn Create
   * @brief Create a platform specific window. (Needs to be specified with
   * compiler flags.)
   */
  static Window* Create(
      const WindowProperties& properties = WindowProperties());
};

}  // namespace engine

#endif  // ENGINE_SRC_CORE_WINDOW_H_
