[package]
name = "lambda-obj-loader"
version = "2023.1.21"
edition = "2021"

[[bin]]
name = "obj-loader"
path = "src/main.rs"

[dependencies]
lambda-rs = { path = "../../crates/lambda-rs", version = "2023.1.26" }
lambda-rs-args = { path = "../../crates/lambda-rs-args", version = "2023.1.26" }
