[package]
name = "lambda-obj-loader"
version = "2023.1.21"
edition = "2021"

[[bin]]
name = "obj-loader"
path = "src/main.rs"

[dependencies]
lambda = { path = "../../lambda", version = "2023.1.26" }
lambda-args = { path = "../../crates/lambda-args", version = "2023.1.26" }
