[package]
name = "lambda_obj_loader"
version = "2022.1.21"
edition = "2021"

[[bin]]
name = "obj_loader"
path = "src/main.rs"

[dependencies]
lambda = { path = "../../lambda" }
lambda-args = { path = "../../crates/lambda-args" }
