repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/daverona/pre-commit-cpp
    rev: 0.6.0
    hooks:
      - id: cpplint
        name: Lint-engine
        args: [
          "--filter=-legal/copyright,-build/include,-build/c++11",
          ]
