repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/daverona/pre-commit-cpp
    rev: 0.6.0
    hooks:
      - id: cpplint
        name: C++ Linter
        args: [
          "--filter=-legal/copyright,-build/include,-build/c++11",
          ]
  - repo: local
    hooks:
      - id: fmt
        args: []
        entry: rustup run nightly cargo fmt --
        language: system
        name: Linting for lambda-rs & tools.
        types: [rust]
