edition="2021"
fn_args_layout="Tall"
force_explicit_abi=true
max_width=80
newline_style="Native"
tab_spaces=2
use_field_init_shorthand=true
ignore = [
	"lambda.rs"
]
# Unstable
unstable_features = true
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports="StdExternalCrate"
