edition="2021"
fn_params_layout="Tall"
force_explicit_abi=true
max_width=80
tab_spaces=2
use_field_init_shorthand=true

# Unstable feature flags
unstable_features = true
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports="StdExternalCrate"
