[package]
name = "lambda"
version = "0.1.0"
edition = "2018"

[lib]
name = "lambda"
path = "src/lambda.rs"

[dependencies]
gfx-hal = "=0.9.0"
winit = "=0.25.0"

# ------------------------------- GFX-RS BACKENDS ------------------------------

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-gl"
version = "=0.9.0"

[target.'cfg(target_os = "macos")'.dependencies.backend]
package = "gfx-backend-metal"
version = "=0.9.0"

[target.'cfg(windows)'.dependencies.backend]
package = "gfx-backend-dx12"
version = "=0.9.0"
