[package]
name = "lambda-rs-logging"
description = "Logging support for lambda-rs"
version = "2023.1.30"
edition = "2021"
license = "MIT"

[lib]
name = "logging"
path = "src/lib.rs"

[dependencies]
once_cell = "1"
