[package]
name = "lambda_rs_demo"
version = "2023.1.25"
edition = "2021"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
lambda = { path = "../../lambda" }

[features]
default = ["lambda/detect-platform"]