name: compile_and_test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test Lambda on ${{ matrix.os }} with ${{ matrix.cpp-compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        cpp-compiler: [ g++-10 ]
        c-compiler: [ gcc-10 ]
        include:
          - os: ubuntu-latest
            target: Linux

          - os: macos-latest
            target: Macos

          - os: windows-latest
            cpp-compiler: cl
            c-compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: ./scripts/setup.sh --within-ci true

      - name: Obtain Randr for glfw on Ubuntu.
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libxrandr-dev

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a release build of lambda
        run: ./scripts/compile_lambda.sh \
            --build Release \
            --cpp-compiler ${{ matrix.cpp-compiler }} \
            --c-compiler ${{ matrix.c-compiler }} \
            --os ${{ matrix.target }} \
            --cores 2
